# Generated by Django 4.2.3 on 2025-02-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_alter_choice_id_alter_course_id_alter_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='grade_point',
            field=models.IntegerField(),
        ),
    ]
